---
title: "1870 Census Visuals"
format:
  jasa-pdf:
    keep-tex: true  
    journal:
      blinded: false
  jasa-html: default
date: last-modified
author:
  - name: Author 1
    acknowledgements: | 
      The authors gratefully acknowledge _please remember to list all relevant funding sources in the non-anonymized (unblinded) version_.
    affiliations:
      - name: University of XXX
        department: Department of YYY
  - name: Author 2
    affiliations:
      - name: University of WWW
        department: Department of ZZZ
abstract: |
  The Statistical Atlas of the 1870's made visuals using data from the 9th Census. We examined the concentric circle visualizations that compared 1860 and 1870 state disabled population growth or decline against standard and overlaid bar charts. The visuals were recreated from data preserved by the Census. Through our analysis of effectiveness, we found systematic bias to underestimate growth in concentric circle charts compared to bar charts. 
keywords:
  - concentric circle charts 
  - bar charts
  - Statistical Atlas 
  - Census Bureau 
bibliography: bibliography.bib  
editor: 
  markdown: 
    wrap: sentence
---

## Introduction

The 1870 Statistical Atlas created visualizations on a wide variety of data spanning 107 pages.
Many of these visualizations would be considered out of the ordinary by today's standards and give us the opportunity to test the perceptual accuracy of these against more commonly used traditional graphics.
This is because there were no real conventions around visuals as people didn't commonly graph data so the Statistical Atlas was pioneer in terms of chart types.
The purpose of this experiment is to analyze these visuals and understand there potential flaws based on graphical perception research that has taken place since.
Over time some forms of visualizations stuck around around and continued to be used while others did not.
We want to examine whether they randomly faded away or if was for good reason.

We will be evaluating concentric circle visualizations created by Fred H. Wines, Secretary of the Illinois State Board of Charities, that show populations of various disabled groups in the 19th century.
The 4 disabled groups represented are the Blind, Deaf-Mutes, Developmentally Disabled, and Mentally Ill.
The populations were presented as circles were the area of the circle is the population of each group of people in each state.
They showed the state by state population for 1860 and 1870 as 1 visual were the smaller circle was inside the larger circle to show the growth or decline over the decade.
These visuals were then placed along a row, showing state to state population comparisons.

### Historical Context of disabled groups

These visuals were created using data gathered and stored from the 9th US Census.
The Census gathered this information to understand disability trends, try and find causes, and get qualitative examples of how these people functioned in society.

-   SEE Historical Notes.qmd for lots of information from the census documents

    -   Explain the terms they used and the context around the words to lay out a framework around why these words were used and then continue to use the words how they laid them out

<!-- -->

-   Talk about the reasoning why the Census tracked this information(this is all in a different write up section)

    -   Find causes/trends with disabilities and the tasks that the disabled were able to complete/care needed for them

    -   talk about the potential limitations they mentioned and errors in stats taken

• 1864: Advocates like Willard argued that proper treatment saves money long term and benefits society in response to ”poorhouses” where the mentally ill were chained up in dark rooms

• 1860s: Push for higher-quality care and rehabilitation for the mentally ill • 1870: Nebraska Asylum for the Insane opened to meet population needs and ensure public safety • 1869-1889: Six more facilities opened across Nebraska to serve scattered populations and various disabled groups • 1913: Bethphage Village was founded due to inadequate care for developmentally disabled populations • 1960s: Large institutional facilities became common • Later Decades: Shift toward smaller care facilities, but the 1990s funding cuts led to many being placed in prisons as cheaper alternatives • Despite societal and economic advancements, care for vulnerable populations has regressed back toward what Willard advocated against

### Theoretical Framework of Concentric Circles

We hypothesize that peoples ability to make judgement based on their perceptions of the concentric circle charts will be inaccurate compared to bar charts.
Moreover, not only do we think there will be a higher absolute error, but also a bias to underestimate growth based on Cleveland and McGill(1984).

-   Read Cleveland and McGill 1984 pages 537-538 for reasoning on why there is a bias

    -   humans apply a non-linear power law mental scaling

    -   length has no inherent bias to it

<!-- -->

-   they had an assumption of sustained growth in populations as the charts only worked well if the populations grew

-   At some point mention how these concentric circle charts do not allow for understanding true populations, just growth/decline and state to state ratios.

The Visual Decoding of Quantitative Information on Graphical Displays of Data (Cleveland and McGill 1987) - page 197

-   area ranks 6th

-   length ranks 3rd

### Alternative Graphics

-   ?

## Historic Visual Accuracy

The Statistical Atlas visuals were created using lithographic printing where images were drawn onto a stone tablet and printed off of it.
This process is complex and more prone to human error which could result in blurry or inaccurately sized images.
We downloaded the high resolution TIFF images from the Census website and used GIMP software to take pixel measurements of the width and height of each one of the circles.
Upon analyzing the data, we found that the top and bottom of the circles were often thick and fuzzy.
Additionally, a lot of the images were slightly misshapen so they are wider than they are tall.

To assess how accurately these represented the true populations according Census data, we obtained 5% micro-sample data from IPUMS(cite IPUMS).
These diameter measurements taken from the visuals were scaled into areas using the formula Area = pi \* r\^2.
These were then divided by a scaling factor based off the known population derived from number of samples in the micro-sample data.
This gave us 1860 and 1870 population values for each state derived from the 2 types of diameter measurements of the concentric circle charts.
The 5% micro-sample data and derived chart data were then compared by plotting the population against each other.
The data should follow a straight y = x line if the data is accurate.
However, we overlooked a crucial element and the micro-sample data was not helpful in determining the accuracy of the charts due to the rarity of the event of a person having one of these disabilities.
The chance a person had any of the 4 disabilities was 0.235% so the sample size was not large enough and resulted in too much variance relative the rarity of these events.

-   INSERT GRAPHS

This led us to looking for full population data and found it for all 4 disability types for the 1870 data so only the accuracy of that could be checked.
Using the same technique described above with the micro-sample data, the 1870 full population data was analyzed.
With 1 exception, we found only small errors, which could potentially be attributed to measurement error on our end or are a result of the blurriness of the images.
However, the 1870 Virginia circles were represented as significantly larger than the Census data populations for several of the disability types.
This closely echos (your research paper), where they found that the minnesota graph was very innacurate which illustrates the problems with these older methods of image creation.
This could be a result of human error in printing or receiving or using the wrong data from the Census.

-   INSERT GRAPHS

## Visual Recreation

The visuals were recreated in R using the ggplot2 package using the Census data for the 2 disability types where the 1860 and 1870 data was available.
The visuals were created from the same data sets in the 3 different chart types being concentric circle, bar, and overlaid bar charts.
In this Statistical Atlas there was not traditional bar charts throughout, but there were part to part bar charts looking at civil war costs(check accuracy)\*\*, so we wanted to compare the concentric circle charts to a reasonable counterpart.
There are key differences, as our overlaid bar charts are part to whole comparisons, similar to the concentric circle charts, but the idea of using a visualization type from the time period remains the same.
Having this same data graphed in 3 different visual forms allows for comparison of the quantitative accuracy in which people can derive the ratios of growth.

## Methods

-   out of the graphs created, we chose 5 pairs of states (10 total states) and asked individuals to make a inner state growth/decline estimate for both states and a 1870 state to state population estimate (3 estimations per visual)

-   participants were randomly given 3 of the 5 visuals so we could test ratios over a larger interval while also keeping total judgements to n \< 30 where people usually start to become disinterested and preform worse

-   for the 3 visuals they received the data in all 3 graph formats(concentric circle, bar, overlaid bar) so we can test how well they compare within persons

-   this is a total of 3 x 3 x 3 = 27 judgements per person

-   study was developed using the Shiny package in R

-   all judgements were an (A/B) where where is the smaller population and B is the larger so estimates were on a 0 to 1 scale

-   true values of these estimates ranged from .18 to .95

-   Study was ran on prolific and received 302 participants ( 302 x 27 = 8154 total judgments)

## 

## Results

## Conclusion

## Disclosure statement

## Supplementary Material {.supplementary}

Title:

:   Brief description.
    (file type)

R-package for MYNEW routine:

:   R-package MYNEW containing code to perform the diagnostic methods described in the article.
    The package also contains all datasets used as examples in the article.
    (GNU zipped tar file)

HIV data set:

:   Data set used in the illustration of MYNEW method in @sec-verify (.txt file).

## BibTeX
