---
title: "1870 Census Visuals"
format:
  jasa-pdf:
    keep-tex: true  
    journal:
      blinded: false
  jasa-html: default
date: last-modified
author:
  - name: Author 1
    acknowledgements: | 
      The authors gratefully acknowledge _please remember to list all relevant funding sources in the non-anonymized (unblinded) version_.
    affiliations:
      - name: University of XXX
        department: Department of YYY
  - name: Author 2
    affiliations:
      - name: University of WWW
        department: Department of ZZZ
abstract: |
  The Statistical Atlas of the 1870's made visuals using data from the 9th Census. We examined the concentric circle visualizations that compared 1860 and 1870 state disabled population growth or decline against standard and overlaid bar charts. The visuals were recreated from data preserved by the Census. Through our analysis of effectiveness, we found systematic bias to underestimate growth in concentric circle charts compared to bar charts. 
keywords:
  - concentric circle charts 
  - bar charts
  - Statistical Atlas 
  - Census Bureau 
bibliography: bibliography.bib  
editor: 
  markdown: 
    wrap: sentence
---

## Introduction (include historical context + theoretical framework into this section with subheadings) {#sec-intro}

The 1870 Statistical Atlas produced various types visuals spanning 107 pages.
Many of these data visualizations are non-traditional by today's standards and give the opportunity to study how effective these are compared to what we often use today.

-   Created by Fred H. Wines, Secretary of the Illinois State Board of Charities

<!-- -->

-   expand on concentric circle visuals

-   provide images of original statistical atlas

### Historical Context of disabled groups

-   Talk about the reasoning why the Census tracked this information(this is all in a different write up section)

    -   Find causes/trends with disabilities and the tasks that the disabled were able to complete/care needed for them

    -   talk about the potential limitations they mentioned and errors in stats taken

• 1864: Advocates like Willard argued that proper treatment saves money long term and benefits society in response to ”poorhouses” where the mentally ill were chained up in dark rooms

• 1860s: Push for higher-quality care and rehabilitation for the mentally ill • 1870: Nebraska Asylum for the Insane opened to meet population needs and ensure public safety • 1869-1889: Six more facilities opened across Nebraska to serve scattered populations and various disabled groups • 1913: Bethphage Village was founded due to inadequate care for developmentally disabled populations • 1960s: Large institutional facilities became common • Later Decades: Shift toward smaller care facilities, but the 1990s funding cuts led to many being placed in prisons as cheaper alternatives • Despite societal and economic advancements, care for vulnerable populations has regressed back toward what Willard advocated against

### Theoretical Framework of Concentric Circles

-   we hypothesize that concentric circle visuals will lead to less accurate estimates due to the exponential growth of area measurements

-   Cleveland and McGill ranked these lower than the alternatives we used due to this reasoning

    -   Will lead to underestimation( find theoretical framework in their study)

-   illusions unique to circle visuals can cause increased errors and bias (ebbinghaus...)

-   lack of scale on charts can also increase estimation difficulties (polar scale is sub-optimal)

    ### Alternative Graphics

    -   Chose bar charts as they are the best for perception according to cleveland and mcgill

    -   chose overlaid bar charts as very similar types of charts were used to it in the statistical atlas(theres was part to part not part to whole) however it seems reasonable the statistical atlas could have used a chart type like it

## Historic Visual Accuracy

-   Visuals were created using lithography so we were unsure on the accuracy in which they were made

<!-- -->

-   used TIFF images from US Census to take pixel measurements using GIMP and then scaled them to population data

-   took height and width measurements and ran comparisons both ways

    -   Found that a lot of the images aren't perfectly round and were often a little wider than tall

-   Got IPUMS 5% microsample data to run comparison against images to test for accuracy

    -   Since these disabilities are such rare events we found this not helpful to test for accuracy because of the massive variability of the micro sample data

    -   Insert micro sample graphs

-   Found 1870 100% population data for all 4 disability types to run the comparison

    -   found that the images are largely accurate, however, Virginia's 1870 population was over represented in multiple instances

    -   Insert 100% population data graphs

## Visual Recreation

-   found 100% population data for 1860 and 1870 of 2 of the disabled groups

-   recreated visuals based on this population data for concentric circles, overlaid bar charts, and bar charts in R

## Methods {#sec-meth}

-   out of the graphs created, we chose 5 pairs of states (10 total states) and asked individuals to make a inner state growth/decline estimate for both states and a 1870 state to state population estimate (3 estimations per visual)

-   participants were randomly given 3 of the 5 visuals so we could test ratios over a larger interval while also keeping total judgements to n \< 30 where people usually start to become disinterested and preform worse

-   for the 3 visuals they received the data in all 3 graph formats(concentric circle, bar, overlaid bar) so we can test how well they compare within persons

-   this is a total of 3 x 3 x 3 = 27 judgements per person

-   study was developed using the Shiny package in R

-   all judgements were an (A/B) where where is the smaller population and B is the larger so estimates were on a 0 to 1 scale

-   true values of these estimates ranged from .18 to .95

-   Study was ran on prolific and received 302 participants ( 302 x 27 = 8154 total judgments)

## Results

-   Model: Error \~ Visualization Type + Pair + Judgment Order+ (1 \| Session ID)

    -   mixed effects model to control for person to person errors as each person sets there own baseline error to not violate independence

    -   error = true value - estimated value

-   Found a .032 increase in error with p \< .001 of concentric circle vs bar charts

    -   This indicates a bias to underestimate growth / larger state population ratio

-   Found a .030 increase in error with p \< .001 of state to state populations compared to inner state estimations

-   Insert table of results

-   inert log of estimated values vs true values

## Conclusion {#sec-conc}

## Disclosure statement

The authors have the following conflicts of interest to declare (or replace with a statement that no conflicts of interest exist).

## Data Availability Statement

Deidentified data have been made available at the following URL: XX.

## Supplementary Material {.supplementary}

Title:

:   Brief description.
    (file type)

R-package for MYNEW routine:

:   R-package MYNEW containing code to perform the diagnostic methods described in the article.
    The package also contains all datasets used as examples in the article.
    (GNU zipped tar file)

HIV data set:

:   Data set used in the illustration of MYNEW method in @sec-verify (.txt file).

## BibTeX

We encourage you to use BibTeX.
If you have, please feel free to use the package natbib with any bibliography style you're comfortable with.
The .bst file agsm has been included here for your convenience.
